query allFeeds($condition: FeedCondition!) {
  allFeeds(condition: $condition) {
    nodes {
      id
      comment
      tenantId
      typeId
      statusId
      createdOn
      createdBy
      feedTypeName
      feedTypeKey
      statusName
      statusKey
      importId
      pending
      started
      complete
      errored
      total
    }
  }
}
